### PR TITLE
Bump dependencies to fix issues with glibc 2.27 and perl 5.26

### PR DESCRIPTION
**Pull request by larkmjc**
Bump dependencies to fix issues with glibc 2.27 and perl 5.26

- Bump e2fsprogs to 1.44.1 to fix issue with glibc 2.27
    
    glibc 2.27 introduces a copy_file_range function that
    clashes with a static function in e2fsprogs 1.43.1
    causing a compile error. It This has been fixed in
    e2fsprogs 1.43.8. Bump to latest e2fsprogs 1.44.1
    
    - http://e2fsprogs.sourceforge.net/e2fsprogs-release.html#1.43.8

- Bump automake to 1.16.1 to fix issue with perl 5.26
    
    Fixes "Unescaped left brace in regex is deprecated, passed
    through in regex" error message when using perl 5.26
    
    - https://lists.gnu.org/archive/html/bug-automake/2017-06/msg00003.html

### CODE REVIEW

**Comment by jim-wilson** [comment]
Please fix the conflict in the patch.  You submitted a patch against branch master, which uses automake 1.15, but you submitted it for branch sifive, which uses 1.15.1.  Branch sifive is what freedom-u-sdk is using, so that looks correct.  I think you need to merge/rebase your branch with sifive to get the patch right.

**Review by jim-wilson — APPROVED** [review]
Needs conflict fixed, but otherwise looks OK.

**Comment by larkmjc** [comment]
I made the commit against the commit id that was in freedom-u-sdk, and there was no branch that corresponded with that commit id. Which branch should we patch? I can respin...

**Comment by jim-wilson** [comment]
The commit in freedom-u-sdk maps to a commit on the sifive branch.  sifive and master have a last common commit of
    commit 78eda27f898c01adee9d219238bca315b4aa3ea5
    Author: Andr\303\251 Hentschel <nerv@dawncrow.de>
    Date:   Thu Jun 16 19:33:46 2016 +0200
The top of the master branch matches a commit in the upstream tree.  So it appears that master is tracking the upstream tree.  Sifive is a commit on master plus local changes.  freedom-u-sdk uses a commit on sifive.

So you need to add your patch to sifive branch.

Or alternatively, merge master with upstream, merge sifive with master, and then update freedom-u-sdk, but that is likely a lot of work, and more likely to break stuff.  It is simpler to continue with your patch which is an incremental change.

**Comment by larkmjc** [comment]
I'm just testing auto automake 1.15.1 on the sifive branch. If it works okay (has resolved the perl 5.26 issue), then we only need the patch to update e2fsprogs to 1.44.1 (for glibc 2.27 copy_file_range clash).

**Pull request closed without merging**
